#ifndef APP_HARDWARE_MAP_H
#define APP_HARDWARE_MAP_H

#include "hardware/i2c.h"

#ifndef APP_HW_DIMMER_ZERO_CROSS_PIN
#define APP_HW_DIMMER_ZERO_CROSS_PIN 2u
#endif

#ifndef APP_HW_DIMMER_GATE_PIN
#define APP_HW_DIMMER_GATE_PIN 3u
#endif

#ifndef APP_HW_ADP910_I2C_FREQUENCY_HZ
#define APP_HW_ADP910_I2C_FREQUENCY_HZ 100000u
#endif

#ifndef APP_HW_ADP910_I2C_ADDRESS
#define APP_HW_ADP910_I2C_ADDRESS 0x25u
#endif

#ifndef APP_HW_ADP910_SENSOR0_I2C_INSTANCE
#define APP_HW_ADP910_SENSOR0_I2C_INSTANCE i2c0
#endif

#ifndef APP_HW_ADP910_SENSOR0_SDA_PIN
#define APP_HW_ADP910_SENSOR0_SDA_PIN 4u
#endif

#ifndef APP_HW_ADP910_SENSOR0_SCL_PIN
#define APP_HW_ADP910_SENSOR0_SCL_PIN 5u
#endif

#ifndef APP_HW_ADP910_SENSOR1_I2C_INSTANCE
#define APP_HW_ADP910_SENSOR1_I2C_INSTANCE i2c1
#endif

#ifndef APP_HW_ADP910_SENSOR1_SDA_PIN
#define APP_HW_ADP910_SENSOR1_SDA_PIN 6u
#endif

#ifndef APP_HW_ADP910_SENSOR1_SCL_PIN
#define APP_HW_ADP910_SENSOR1_SCL_PIN 7u
#endif

#endif
