#ifndef BLOWER_APP_CONFIG_H
#define BLOWER_APP_CONFIG_H

#include "app/hardware_map.h"

#define DIMMER_ZC_GPIO APP_HW_DIMMER_ZERO_CROSS_PIN
#define DIMMER_GATE_GPIO APP_HW_DIMMER_GATE_PIN

#define DIMMER_MAINS_HALF_CYCLE_US 10000u

#define DIMMER_GATE_PULSE_US 100u

#define DIMMER_ZC_DEBOUNCE_US 1500u

#endif
